# Generated by Django 5.0 on 2024-01-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.PositiveIntegerField()),
                ('ADD', models.FloatField()),
                ('TS', models.FloatField()),
                ('Python', models.FloatField()),
                ('Teledétecion', models.FloatField()),
            ],
        ),
    ]
