# Generated by Django 5.0 on 2024-01-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='Teledétecion',
            new_name='Teledetecion',
        ),
    ]
