# Generated by Django 5.0 on 2024-01-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_teledétecion_note_teledetecion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_number', models.PositiveIntegerField()),
                ('Prenom', models.CharField(max_length=50)),
                ('Nom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('CIN', models.CharField(max_length=50)),
            ],
        ),
    ]
